--liquibase formatted sql
--changeset magarusik:create-table-user_authority

create table user_authority
(
    id           bigint primary key not null generated by default as identity,
    user_id      bigint             not null references users (id),
    authority_id bigint             not null references authority (id)
)