--liquibase formatted sql
--changeset magarusik:create-table-question_type

create table question_type
(
    id    bigint primary key not null generated by default as identity,
    title varchar            not null unique
);