--liquibase formatted sql
--changeset magarusik:create-table-users

create table users
(
    id            bigint primary key not null generated by default as identity,
    username      varchar            not null unique,
    email         varchar unique,
    first_name    varchar,
    last_name     varchar,
    patronymic    varchar,
    date_of_birth date,
    course        int,
    group_name    varchar
);