--liquibase formatted sql
--changeset magarusik:create-table-users

create table user_profile
(
    id            bigint primary key not null generated by default as identity,
    user_id       bigint             not null unique references user_management."users" (id),
    email         varchar unique,
    first_name    varchar,
    last_name     varchar,
    patronymic    varchar,
    date_of_birth date,
    course        int,
    group_name    varchar
);