spring:
  datasource:
    username: postgres
    password: 1312
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  servlet:
    context-path: /student-tester/api/v1

springdoc:
  api-docs:
    path: /docs
  show-actuator: true
  swagger-ui:
    path: /docs-ui.html