spring:
  application:
    name: student-testing-service

  datasource:
    username: magarusik
    password: 1312
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=testing
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    default-schema: testing

  security:
    user:
      name: testing-service-client
      password: testing
      roles:
        - SERVICE

server:
  port: 9090
  servlet:
    context-path: /api/v1/testing-service/