spring:
  application:
    name: student-testing-client
  datasource:
    username: ${DB_USERNAME:magarusik}
    password: ${DB_PASSWORD:1312}
    url: jdbc:postgresql://localhost:5432/${DB_NAME:postgres}?currentSchema=${DB_SCHEMA:user_management}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    default-schema: ${DB_NAME:user_management}

  devtools:
    livereload:
      port: 35731

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1/client/

testing:
  services:
    testing-service:
      uri: ${SERVICE_URI:http://localhost:9090}
      context-path: ${SERVICE_CONTEXT_PATH:/api/v1/service/}