spring:
  application:
    name: student-testing-client

server:
  port: 8080
  servlet:
    context-path: /api/v1/testing-client/

testing:
  services:
    testing-service:
      uri: http://localhost:9090