spring:
  application:
    name: student-testing-client

server:
  port: 8080
  servlet:
    context-path: /api/v1/testing-client/

ru:
  magarusik:
    service:
      uri: http://localhost:9090/api/v1/testing-service