--liquibase formatted sql
--changeset magarusik:create-table-authority

create table authority
(
    id        bigint primary key not null generated by default as identity,
    authority varchar            not null unique
)