--liquibase formatted sql
--changeset magarusik:create-table-tests

create table tests
(
    id           bigint primary key not null generated by default as identity,
    title        varchar            not null unique,
    created_date date               not null
);