--liquibase formatted sql
--changeset magarusik:create-table-question_types

create table question_types
(
    id    bigint primary key not null generated by default as identity,
    title varchar            not null unique
);