--liquibase formatted sql
--changeset magarusik:create-table-questions

create table questions
(
    id               bigint primary key not null generated by default as identity,
    title            varchar            not null,
    test_id          bigint             not null references tests (id),
    question_type_id bigint             not null references question_types (id)
);