--liquibase formatted sql
--changeset magarusik:create-table-user_role

create table user_role
(
    id    bigint primary key not null generated by default as identity,
    title varchar            not null unique
);