--liquibase formatted sql
--changeset magarusik:create-table-user_roles

create table user_roles
(
    id    bigint primary key not null generated by default as identity,
    title varchar            not null unique
);