--liquibase formatted sql
--changeset magarusik:create-table-users

create table users
(
    id       bigint primary key not null generated by default as identity,
    login    varchar            not null unique,
    password varchar            not null,
    role_id  bigint             not null references user_roles (id)
);